const SET_PERSONS = 'persons/SET_PERSONS'
const SET_PERSON = 'persons/SET_PERSON'
const FETCHING_PERSON = 'person/FETCHING_PERSON'
const SET_PERSONS_FILTER = 'person/SET_PERSONS_FILTER'

export default {
  SET_PERSON,
  SET_PERSONS,
  FETCHING_PERSON,
  SET_PERSONS_FILTER
}
